name: Deploy Resume

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHCR_TOKEN }}
          publish_dir: ./public  # Adjust directory if different
